name: serde_json
description: Rust serde compatible Serializer Deserializer
version: 0.0.1
repository: https://github.com/mcmah309/serde_json

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  macros: ^0.1.0-main.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
